### ISSUE TITLE
Nil reference error with gdrive.NewRowReader and no filter

### ISSUE THREAD

**Issue by alexellis** [gomodules/gdrive-utils#3]
I want to get all of the rows back, so I ran this code without a filter and it caused a nil reference.

```go
func ListEmails(err error, srv *sheets.Service, spreadsheetId string, sheetName string, header string) sets.String {
	var filter *gdrive.Filter
	sheetReader, err := gdrive.NewRowReader(srv, spreadsheetId, sheetName, filter)
	if err != nil {
		panic(err)
	}

	v, err := sheetReader.ReadAll()
	if err != nil {
		panic(err)
	}
	for i, row := range v {
		fmt.Printf("[%d] %v\n", i, row)
	}

	// reader, err := gdrive.NewColumnReader(srv, spreadsheetId, sheetName, header)
	// if err != nil {
	// 	panic(err)
	// }

	// cols, err := reader.ReadAll()
	// if err != nil {
	// 	panic(err)
	// }

	emails := sets.NewString()
	// for _, row := range cols {
	// 	emails.Insert(row...)
	// }
	return emails
}
```

Error:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a0cdc]

goroutine 1 [running]:
gomodules.xyz/gdrive-utils.NewRowReader(0xc0001a12f0, 0x9d3d5a, 0x2c, 0x9c4317, 0x10, 0x0, 0xc0000103a8, 0xc0001a12c0, 0xd52ae0)
        /home/alex/go/pkg/mod/gomodules.xyz/gdrive-utils@v0.0.0-20210829112507-325ac7ee9927/reader.go:131 +0x1fc
main.ListEmails(0x0, 0x0, 0xc0001a12f0, 0x9d3d5a, 0x2c, 0x9c4317, 0x10, 0x9c2b4d, 0xd, 0xc000000180)
        /home/alex/go/src/github.com/tamalsaha/sheet-demo/main.go:36 +0x7d
main.main()
        /home/alex/go/src/github.com/tamalsaha/sheet-demo/main.go:30 +0x1bb
exit status 2
```

It should work with a nil filter since the signature takes a nilable filter.

In reader.go I see:

```go
	idx, err := filter.By(resp.Values[0])
	if err != nil {
		return nil, err
	}
```

However, this should be `if filter != nil {` to avoid the error.

Context: I'm trying to use this library to import some data from a Google sheet.

**Comment by tamalsaha** [comment]
Fixed
https://github.com/gomodules/gdrive-utils/commit/df947ef32c47879e89c313de03b1f9c70a5f478b
